#lang sicp
(define (compose f g)
  (lambda (x) (f (g x))))
(define (repeated f n)
  (define (iter i acc)
    (if (= i n)
        acc
        (iter (+ i 1) (compose f acc))))
  (iter 1 f))
(define dx 0.00001)
(define (smooth f)
  (lambda (x) (/ (+ (f (- x dx)) (f x) (f (+ x dx))) 3)))
(define (square x) (* x x))
((smooth square) 2)
(((repeated smooth 10) square) 25)
